server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
            allowed-headers:
              - "*"
            allow-credentials: true
      routes:
        - id: auth-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/authentication/**
          filters:
            - AuthenticationFilter

        - id: account-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter

#        - id: reservation-service
#          uri: http://reservation-service:8084/
#          predicates:
#            - Path=/api/reservation/**
#          filters:
#            - AuthenticationFilter
#
#        - id: property-service
#          uri: http://property-service:8085/
#          predicates:
#            - Path=/api/property/**
#          filters:
#            - AuthenticationFilter
#            - AdminRouteFilter
