apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: nattystar/waa-notification:2.7.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8085 # port to access the app in the conta
        env:  #enviromental variables
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: vault
                key: DB_USER_NAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vault
                key: DB_PASSWORD
          - name: DB_NAME
            value: notification
          - name: SIGN_KEY
            valueFrom:
              secretKeyRef:
                name: vault
                key: SIGN_KEY
                

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 8085


    

