apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: nattystar/waa-order
        imagePullPolicy: Always
        ports:
        - containerPort: 8083 # port to access the app in the conta
        env:  #enviromental variables
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: vault
                key: DB_USER_NAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vault
                key: DB_PASSWORD
          - name: DB_NAME
            value: order
          - name: SIGN_KEY
            valueFrom:
              secretKeyRef:
                name: vault
                key: SIGN_KEY
                

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083


    

