apiVersion: v1
kind: Secret
metadata:
  name: vault
type: Opaque
data:
  DB_USER_NAME: d2ViYXBwbGljYXRpb25hcmNoaXRlY3R1cmU= #webapplicationarchitecture
  DB_PASSWORD: d2Fh #waa
  SIGN_KEY: VE9QLVNFQ1JFVA== #TOP-SECRET
  password: <Password>
