apiVersion: apps/v1
kind: Deployment
metadata:
  name: zillow-property-deployment
  labels:
    app: zillow-property
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zillow-property
  template:
    metadata:
      labels:
        app: zillow-property
    spec:
      containers:
        - name: zillow-property
          image: tsidk29/zillow-property
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084 # port to access the app in the container
#          env: #setting enviromental variable for the container
#            - name: DB_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: vault
#                  key: DB_USER_NAME
#            - name: DB_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: vault
#                  key: DB_PASSWORD
#            - name: DB_NAME
#              value: zillow-property
---
apiVersion: v1
kind: Service
metadata:
  name: zillow-property-service
spec:
  selector:
    app: zillow-property
  #     type: NodePort # LoadBalancer for or NodePort external service
  ports:
    - protocol: TCP
      port: 8084 # port to access the pod
      targetPort: 8084 # must be the same as the containerPort
#      nodePort: 30200 ## for external service port